### ISSUE TITLE
ResultCode改进（顺带测试github的issues）

### ISSUE THREAD

**Issue by Tidy-Bear** [Suphx/vm#1]
目前**Controller**响应**前端**的逻辑如下：
1. 在*ResultCode*类中预置响应码（成员常量，包括标准的200、400、500，以及自定义）
2. 按具体逻辑，调用*ResultFactory*工厂类的静态方法*buildSuccessResult()*、*buildFailResult()*，返回*Result*类对象；如果要向**前端**返回msg或data，则把它们作实参

建议将*ResultCode*从**Class**改成**Enum**
1. 原本就是常量类，**Enum**比普通的**Class**更合适
2. 比普通的数字更具语义（200 -> SUCCESS，400 -> FAIL）
3. 有效防止其它程序猿写错成没有定义的响应码（int）

举个栗子，程序猿现在想返回正常的200
（一）不用枚举
由于程序猿加班太累，在200末尾多补了个0，写成了2000（假定系统没有定义过2000，甚至2000有其它含义）
```java
Result buildResult(int code, String msg, Object data) {
    // ...
}
```
按照上述定义，传入2000编译器不报错，毕竟的确是int类型，但实际肯定是有误的

（二）使用枚举
现在将*ResultCode*改成**Enum**，定义如下
```java
public Enum ResultCode {
    SUCCESS(200, "成功"),
    FAIL(400, "不存在"),
    INTERNAL_SERVER_ERROR(500, "服务器错误");

    private final int code;
    private final String msg;

    ResultCode(int code, String msg) {
        this.code = code;
        this.msg = msg;
    }

    public int getCode() {
        return this.code;
    }

    public int getMsg() {
        return this.msg;
    }
}
```
对应方法改为
```java
Result buildResult(ResultCode code, String msg, Object data) {}
```
这样，编译器规定必须传入枚举常量，而不管程序猿再怎么累，至少也知道传的是SUCCESS而非其它啦
```java
buildResult(ResultCode.SUCCESS, msg, data)
```

综上，在Java 1.5引入Enum后，推荐常量类全部改为枚举！

**Comment by Suphx** [comment]
已更新
